// Generated by npm run fetch-fabric. Do not edit manually.
export const FABRIC_COMMIT = 'b682dad740f24e85ce9a48d23babc6780dd476ac';
export const FABRIC_PATTERNS: { name: string; description: string }[] = [
  {
    name: 'agility_story',
    description: 'Generate a user story and acceptance criteria in JSON format based on the given topic.',
  },
  {
    name: 'ai',
    description:
      'Interpret questions deeply and provide concise, insightful answers in Markdown bullet points.',
  },
  {
    name: 'analyze_answers',
    description:
      'Evaluate quiz answers for correctness based on learning objectives and generated quiz questions.',
  },
  {
    name: 'analyze_bill',
    description:
      'Analyzes legislation to identify overt and covert goals, examining bills for hidden agendas and true intentions.',
  },
  {
    name: 'analyze_bill_short',
    description:
      'Provides a concise analysis of legislation, identifying overt and covert goals in a brief, structured format.',
  },
  {
    name: 'analyze_candidates',
    description: 'Compare and contrast two political candidates based on key issues and policies.',
  },
  {
    name: 'analyze_cfp_submission',
    description:
      'Review and evaluate conference speaking session submissions based on clarity, relevance, depth, and engagement potential.',
  },
  {
    name: 'analyze_claims',
    description:
      'Analyse and rate truth claims with evidence, counter-arguments, fallacies, and final recommendations.',
  },
  {
    name: 'analyze_comments',
    description:
      'Evaluate internet comments for content, categorize sentiment, and identify reasons for praise, criticism, and neutrality.',
  },
  {
    name: 'analyze_debate',
    description:
      'Rate debates on insight, emotionality, and present an unbiased, thorough analysis of arguments, agreements, and disagreements.',
  },
  {
    name: 'analyze_discord_structure',
    description:
      'Analyze Discord server structures for organizational issues, permissions, and optimization.',
  },
  {
    name: 'analyze_email_headers',
    description:
      'Provide cybersecurity analysis and actionable insights on SPF, DKIM, DMARC, and ARC email header results.',
  },
  {
    name: 'analyze_incident',
    description:
      'Efficiently extract and organize key details from cybersecurity breach articles, focusing on attack type, vulnerable components, attacker and target info, incident details, and remediation steps.',
  },
  {
    name: 'analyze_interviewer_techniques',
    description:
      'This exercise involves analyzing interviewer techniques, identifying their unique qualities, and succinctly articulating what makes them stand out in a clear, simple format.',
  },
  {
    name: 'analyze_logs',
    description:
      'Analyse server log files to identify patterns, anomalies, and issues, providing data-driven insights and recommendations for improving server reliability and performance.',
  },
  {
    name: 'analyze_malware',
    description:
      "Analyse malware details, extract key indicators, techniques, and potential detection strategies, and summarize findings concisely for a malware analyst's use in identifying and responding to threats.",
  },
  {
    name: 'analyze_military_strategy',
    description:
      'Analyse a historical battle, offering in-depth insights into strategic decisions, strengths, weaknesses, tactical approaches, logistical factors, pivotal moments, and consequences for a comprehensive military evaluation.',
  },
  {
    name: 'analyze_mistakes',
    description:
      'Analyse past mistakes in thinking patterns, map them to current beliefs, and offer recommendations to improve accuracy in predictions.',
  },
  {
    name: 'analyze_monetization_opportunities',
    description:
      'Identifies monetization opportunities in creator content by aligning affiliate commerce, sponsorships, digital products, and communities with audience intent, effort level, and time sensitivity.',
  },
  {
    name: 'analyze_paper',
    description:
      'Analyses research papers by summarizing findings, evaluating rigor, and assessing quality to provide insights for documentation and review.',
  },
  {
    name: 'analyze_paper_simple',
    description:
      'Analyzes academic papers with a focus on primary findings, research quality, and study design evaluation.',
  },
  {
    name: 'analyze_patent',
    description:
      "Analyse a patent's field, problem, solution, novelty, inventive step, and advantages in detail while summarizing and extracting keywords.",
  },
  {
    name: 'analyze_personality',
    description:
      'Performs a deep psychological analysis of a person in the input, focusing on their behavior, language, and psychological traits.',
  },
  {
    name: 'analyze_presentation',
    description:
      "Reviews and critiques presentations by analyzing the content, speaker's underlying goals, self-focus, and entertainment value.",
  },
  {
    name: 'analyze_product_feedback',
    description:
      'A prompt for analyzing and organizing user feedback by identifying themes, consolidating similar comments, and prioritizing them based on usefulness.',
  },
  {
    name: 'analyze_proposition',
    description:
      'Analyzes a ballot proposition by identifying its purpose, impact, arguments for and against, and relevant background information.',
  },
  {
    name: 'analyze_prose',
    description:
      'Evaluates writing for novelty, clarity, and prose, providing ratings, improvement recommendations, and an overall score.',
  },
  {
    name: 'analyze_prose_json',
    description:
      'Evaluates writing for novelty, clarity, prose, and provides ratings, explanations, improvement suggestions, and an overall score in a JSON format.',
  },
  {
    name: 'analyze_prose_pinker',
    description:
      "Evaluates prose based on Steven Pinker's The Sense of Style, analyzing writing style, clarity, and bad writing elements.",
  },
  {
    name: 'analyze_risk',
    description:
      'Conducts a risk assessment of a third-party vendor, assigning a risk score and suggesting security controls based on analysis of provided documents and vendor website.',
  },
  {
    name: 'analyze_sales_call',
    description:
      'Rates sales call performance across multiple dimensions, providing scores and actionable feedback based on transcript analysis.',
  },
  {
    name: 'analyze_spiritual_text',
    description:
      'Compares and contrasts spiritual texts by analyzing claims and differences with the King James Bible.',
  },
  {
    name: 'analyze_tech_impact',
    description:
      'Analyzes the societal impact, ethical considerations, and sustainability of technology projects, evaluating their outcomes and benefits.',
  },
  {
    name: 'analyze_terraform_plan',
    description:
      'Analyzes Terraform plan outputs to assess infrastructure changes, security risks, cost implications, and compliance considerations.',
  },
  {
    name: 'analyze_threat_report',
    description:
      'Extracts surprising insights, trends, statistics, quotes, references, and recommendations from cybersecurity threat reports, summarizing key findings and providing actionable information.',
  },
  {
    name: 'analyze_threat_report_cmds',
    description:
      'Extract and synthesize actionable cybersecurity commands from provided materials, incorporating command-line arguments and expert insights for pentesters and non-experts.',
  },
  {
    name: 'analyze_threat_report_trends',
    description:
      'Extract up to 50 surprising, insightful, and interesting trends from a cybersecurity threat report in markdown format.',
  },
  {
    name: 'answer_interview_question',
    description:
      "Generates concise, tailored responses to technical interview questions, incorporating alternative approaches and evidence to demonstrate the candidate's expertise and experience.",
  },
  {
    name: 'apply_ul_tags',
    description:
      'Apply standardized content tags to categorize topics like AI, cybersecurity, politics, and culture.',
  },
  {
    name: 'ask_secure_by_design_questions',
    description:
      'Generates a set of security-focused questions to ensure a project is built securely by design, covering key components and considerations.',
  },
  {
    name: 'ask_uncle_duke',
    description:
      'Coordinates a team of AI agents to research and produce multiple software development solutions based on provided specifications, and conducts detailed code reviews to ensure adherence to best practices.',
  },
  {
    name: 'audit_consent',
    description:
      'Evaluates whether consent in interactions or agreements is genuine or manufactured by analyzing power asymmetries, information gaps, alternatives, and coercion using a five-test framework.',
  },
  {
    name: 'audit_transparency',
    description:
      'Audits decisions, systems, and algorithms for explainability across five dimensions, assessing whether opacity is justified or serves to conceal harm from affected parties.',
  },
  {
    name: 'capture_thinkers_work',
    description:
      'Analyze philosophers or philosophies and provide detailed summaries about their teachings, background, works, advice, and related concepts in a structured template.',
  },
  {
    name: 'check_agreement',
    description:
      'Analyze contracts and agreements to identify important stipulations, issues, and potential gotchas, then summarize them in Markdown.',
  },
  {
    name: 'check_falsifiability',
    description:
      'Evaluates whether claims, definitions, frameworks, and arguments meet the standard of falsifiability — whether they can be tested and potentially proven wrong.',
  },
  {
    name: 'clean_text',
    description:
      'Fix broken or malformatted text by correcting line breaks, punctuation, capitalization, and paragraphs without altering content or spelling.',
  },
  {
    name: 'coding_master',
    description:
      'Explain a coding concept to a beginner, providing examples, and formatting code in markdown with specific output sections like ideas, recommendations, facts, and insights.',
  },
  {
    name: 'compare_and_contrast',
    description:
      'Compare and contrast a list of items in a markdown table, with items on the left and topics on top.',
  },
  {
    name: 'concall_summary',
    description:
      'Analyzes earnings and conference call transcripts to extract management commentary, analyst Q&A, financial insights, risks, and executive summaries.',
  },
  {
    name: 'convert_to_markdown',
    description:
      'Convert content to clean, complete Markdown format, preserving all original structure, formatting, links, and code blocks without alterations.',
  },
  {
    name: 'create_5_sentence_summary',
    description:
      'Create concise summaries or answers to input at 5 different levels of depth, from 5 words to 1 word.',
  },
  {
    name: 'create_academic_paper',
    description:
      'Generate a high-quality academic paper in LaTeX format with clear concepts, structured content, and a professional layout.',
  },
  {
    name: 'create_ai_jobs_analysis',
    description:
      "Analyze job categories' susceptibility to automation, identify resilient roles, and provide strategies for personal adaptation to AI-driven changes in the workforce.",
  },
  {
    name: 'create_aphorisms',
    description: 'Find and generate a list of brief, witty statements.',
  },
  {
    name: 'create_art_prompt',
    description:
      'Generates a detailed, compelling visual description of a concept, including stylistic references and direct AI instructions for creating art.',
  },
  {
    name: 'create_bd_issue',
    description:
      'Transform natural language descriptions into optimal bd create commands for issue tracking.',
  },
  {
    name: 'create_better_frame',
    description:
      'Identifies and analyzes different frames of interpreting reality, emphasizing the power of positive, productive lenses in shaping outcomes.',
  },
  {
    name: 'create_coding_feature',
    description:
      'Generates secure and composable code features using modern technology and best practices from project specifications.',
  },
  {
    name: 'create_coding_project',
    description: 'Generate wireframes and starter code for any coding ideas that you have.',
  },
  {
    name: 'create_command',
    description:
      'Helps determine the correct parameters and switches for penetration testing tools based on a brief description of the objective.',
  },
  {
    name: 'create_conceptmap',
    description:
      'Transforms unstructured text or markdown content into an interactive HTML concept map using Vis.js by extracting key concepts and their logical relationships.',
  },
  {
    name: 'create_cyber_summary',
    description:
      'Summarizes cybersecurity threats, vulnerabilities, incidents, and malware with a 25-word summary and categorized bullet points, after thoroughly analyzing and mapping the provided input.',
  },
  {
    name: 'create_design_document',
    description:
      'Creates a detailed design document for a system using the C4 model, addressing business and security postures, and including a system context diagram.',
  },
  {
    name: 'create_design_system',
    description: 'Create comprehensive CSS design systems with tokens, typography, spacing, and components.',
  },
  {
    name: 'create_diy',
    description:
      'Creates structured "Do It Yourself" tutorial patterns by analyzing prompts, organizing requirements, and providing step-by-step instructions in Markdown format.',
  },
  {
    name: 'create_excalidraw_visualization',
    description:
      'Creates complex Excalidraw diagrams to visualize relationships between concepts and ideas in structured format.',
  },
  {
    name: 'create_flash_cards',
    description:
      'Creates flashcards for key concepts, definitions, and terms with question-answer format for educational purposes.',
  },
  {
    name: 'create_formal_email',
    description:
      'Crafts professional, clear, and respectful emails by analyzing context, tone, and purpose, ensuring proper structure and formatting.',
  },
  {
    name: 'create_git_diff_commit',
    description:
      'Generates Git commands and commit messages for reflecting changes in a repository, using conventional commits and providing concise shell commands for updates.',
  },
  {
    name: 'create_golden_rules',
    description:
      'Extract enforceable rules from codebases to prevent common mistakes and ensure consistency.',
  },
  {
    name: 'create_graph_from_input',
    description:
      'Generates a CSV file with progress-over-time data for a security program, focusing on relevant metrics and KPIs.',
  },
  {
    name: 'create_hormozi_offer',
    description:
      'Creates a customized business offer based on principles from Alex Hormozi\'s book, "$100M Offers."',
  },
  {
    name: 'create_idea_compass',
    description:
      'Organizes and structures ideas by exploring their definition, evidence, sources, and related themes or consequences.',
  },
  {
    name: 'create_investigation_visualization',
    description:
      'Creates detailed Graphviz visualizations of complex input, highlighting key aspects and providing clear, well-annotated diagrams for investigative analysis and conclusions.',
  },
  {
    name: 'create_keynote',
    description:
      'Creates TED-style keynote presentations with a clear narrative, structured slides, and speaker notes, emphasizing impactful takeaways and cohesive flow.',
  },
  {
    name: 'create_loe_document',
    description:
      'Creates detailed Level of Effort documents for estimating work effort, resources, and costs for tasks or projects.',
  },
  {
    name: 'create_logo',
    description:
      'Creates simple, minimalist company logos without text, generating AI prompts for vector graphic logos based on input.',
  },
  {
    name: 'create_markmap_visualization',
    description:
      'Transforms complex ideas into clear visualizations using MarkMap syntax, simplifying concepts into diagrams with relationships, boxes, arrows, and labels.',
  },
  {
    name: 'create_mermaid_visualization',
    description:
      'Creates detailed, standalone visualizations of concepts using Mermaid (Markdown) syntax, ensuring clarity and coherence in diagrams.',
  },
  {
    name: 'create_mermaid_visualization_for_github',
    description:
      'Creates standalone, detailed visualizations using Mermaid (Markdown) syntax to effectively explain complex concepts, ensuring clarity and precision.',
  },
  {
    name: 'create_micro_summary',
    description:
      'Summarizes content into a concise, 20-word summary with main points and takeaways, formatted in Markdown.',
  },
  {
    name: 'create_mnemonic_phrases',
    description:
      'Creates memorable mnemonic sentences from given words to aid in memory retention and learning.',
  },
  {
    name: 'create_network_threat_landscape',
    description:
      'Analyzes open ports and services from a network scan and generates a comprehensive, insightful, and detailed security threat report in Markdown.',
  },
  {
    name: 'create_newsletter_entry',
    description:
      'Condenses provided article text into a concise, objective, newsletter-style summary with a title in the style of Frontend Weekly.',
  },
  {
    name: 'create_npc',
    description:
      'Generates a detailed D&D 5E NPC, including background, flaws, stats, appearance, personality, goals, and more in Markdown format.',
  },
  {
    name: 'create_pattern',
    description:
      "Extracts, organizes, and formats LLM/AI prompts into structured sections, detailing the AI's role, instructions, output format, and any provided examples for clarity and accuracy.",
  },
  {
    name: 'create_prd',
    description: 'Creates a precise Product Requirements Document (PRD) in Markdown based on input.',
  },
  {
    name: 'create_prediction_block',
    description:
      'Extracts and formats predictions from input into a structured Markdown block for a blog post.',
  },
  {
    name: 'create_quiz',
    description:
      'Creates a three-phase reading plan based on an author or topic to help the user become significantly knowledgeable, including core, extended, and supplementary readings.',
  },
  {
    name: 'create_reading_plan',
    description:
      'Generates review questions based on learning objectives from the input, adapted to the specified student level, and outputs them in a clear markdown format.',
  },
  {
    name: 'create_recursive_outline',
    description:
      'Breaks down complex tasks or projects into manageable, hierarchical components with recursive outlining for clarity and simplicity.',
  },
  {
    name: 'create_report_finding',
    description:
      'Creates a detailed, structured security finding report in markdown, including sections on Description, Risk, Recommendations, References, One-Sentence-Summary, and Quotes.',
  },
  {
    name: 'create_rpg_summary',
    description:
      'Summarizes an in-person RPG session with key events, combat details, player stats, and role-playing highlights in a structured format.',
  },
  {
    name: 'create_security_update',
    description:
      'Creates concise security updates for newsletters, covering stories, threats, advisories, vulnerabilities, and a summary of key issues.',
  },
  {
    name: 'create_show_intro',
    description:
      'Creates compelling short intros for podcasts, summarizing key topics and themes discussed in the episode.',
  },
  {
    name: 'create_sigma_rules',
    description:
      'Extracts Tactics, Techniques, and Procedures (TTPs) from security news and converts them into Sigma detection rules for host-based detections.',
  },
  {
    name: 'create_slides',
    description:
      "Transforms content into engaging Reveal.js HTML slideshows with minimal text, using inline SVG illustrations, charts, and diagrams to visually support the presenter's narrative.",
  },
  {
    name: 'create_story_about_people_interaction',
    description:
      'Analyze two personas, compare their dynamics, and craft a realistic, character-driven story from those insights.',
  },
  {
    name: 'create_story_about_person',
    description:
      'Creates compelling, realistic short stories based on psychological profiles, showing how characters navigate everyday problems using strategies consistent with their personality traits.',
  },
  {
    name: 'create_story_explanation',
    description:
      'Summarizes complex content in a clear, approachable story format that makes the concepts easy to understand.',
  },
  {
    name: 'create_stride_threat_model',
    description:
      'Create a STRIDE-based threat model for a system design, identifying assets, trust boundaries, data flows, and prioritizing threats with mitigations.',
  },
  {
    name: 'create_summary',
    description:
      'Summarizes content into a 20-word sentence, 10 main points (16 words max), and 5 key takeaways in Markdown format.',
  },
  {
    name: 'create_tags',
    description:
      'Identifies at least 5 tags from text content for mind mapping tools, including authors and existing tags if present.',
  },
  {
    name: 'create_threat_scenarios',
    description:
      'Identifies likely attack methods for any system by providing a narrative-based threat model, balancing risk and opportunity.',
  },
  {
    name: 'create_ttrc_graph',
    description:
      'Creates a CSV file showing the progress of Time to Remediate Critical Vulnerabilities over time using given data.',
  },
  {
    name: 'create_ttrc_narrative',
    description:
      'Creates a persuasive narrative highlighting progress in reducing the Time to Remediate Critical Vulnerabilities metric over time.',
  },
  {
    name: 'create_upgrade_pack',
    description:
      'Extracts world model and task algorithm updates from content, providing beliefs about how the world works and task performance.',
  },
  {
    name: 'create_user_story',
    description:
      'Writes concise and clear technical user stories for new features in complex software programs, formatted for all stakeholders.',
  },
  {
    name: 'create_video_chapters',
    description:
      'Extracts interesting topics and timestamps from a transcript, providing concise summaries of key moments.',
  },
  {
    name: 'create_visualization',
    description:
      'Transforms complex ideas into visualizations using intricate ASCII art, simplifying concepts where necessary.',
  },
  {
    name: 'detect_mind_virus',
    description:
      'Detects "mind viruses" — ideas or belief systems that spread by exploiting cognitive shortcuts (fear, guilt, identity) while resisting correction through logic or evidence.',
  },
  {
    name: 'detect_silent_victims',
    description:
      'Analyzes actions, policies, or systems to identify parties harmed but unable to speak up — future generations, voiceless groups, unaware individuals, diffuse populations, or structural victims.',
  },
  {
    name: 'dialog_with_socrates',
    description:
      'Engages in deep, meaningful dialogues to explore and challenge beliefs using the Socratic method.',
  },
  {
    name: 'enrich_blog_post',
    description:
      'Enhances Markdown blog files by applying instructions to improve structure, visuals, and readability for HTML rendering.',
  },
  {
    name: 'explain_code',
    description:
      'Explains code, security tool output, configuration text, and answers questions based on the provided input.',
  },
  {
    name: 'explain_docs',
    description:
      'Improves and restructures tool documentation into clear, concise instructions, including overviews, usage, use cases, and key features.',
  },
  {
    name: 'explain_math',
    description: 'Helps you understand mathematical concepts in a clear and engaging way.',
  },
  {
    name: 'explain_project',
    description:
      'Summarizes project documentation into clear, concise sections covering the project, problem, solution, installation, usage, and examples.',
  },
  {
    name: 'explain_terms',
    description:
      'Produces a glossary of advanced terms from content, providing a definition, analogy, and explanation of why each term matters.',
  },
  {
    name: 'explain_terms_and_conditions',
    description:
      'Analyzes Terms and Conditions and legal agreements, translating complex legalese into plain English, identifying red flags, hidden fees, and privacy risks, with a final verdict on whether to sign.',
  },
  {
    name: 'export_data_as_csv',
    description: 'Extracts and outputs all data structures from the input in properly formatted CSV data.',
  },
  {
    name: 'extract_affiliate_products',
    description:
      'Extracts commercial products, tools, services, and brands from content transcripts, separating sponsored from organic mentions and estimating commission tiers for affiliate opportunities.',
  },
  {
    name: 'extract_algorithm_update_recommendations',
    description:
      'Extracts concise, practical algorithm update recommendations from the input and outputs them in a bulleted list.',
  },
  {
    name: 'extract_all_quotes',
    description:
      'Extract all inspirational and educational quotes from content including podcasts and essays.',
  },
  {
    name: 'extract_alpha',
    description:
      'Extracts the most novel and surprising ideas ("alpha") from content, inspired by information theory.',
  },
  {
    name: 'extract_article_wisdom',
    description:
      'Extracts surprising, insightful, and interesting information from content, categorizing it into sections like summary, ideas, quotes, facts, references, and recommendations.',
  },
  {
    name: 'extract_bd_ideas',
    description: 'Extract actionable ideas from content and transform into bd create commands.',
  },
  {
    name: 'extract_book_ideas',
    description:
      "Extracts and outputs 50 to 100 of the most surprising, insightful, and interesting ideas from a book's content.",
  },
  {
    name: 'extract_book_recommendations',
    description:
      "Extracts and outputs 50 to 100 practical, actionable recommendations from a book's content.",
  },
  {
    name: 'extract_business_ideas',
    description:
      'Extracts top business ideas from content and elaborates on the best 10 with unique differentiators.',
  },
  {
    name: 'extract_characters',
    description:
      "Identify all characters (human and non-human), resolve their aliases and pronouns into canonical names, and produce detailed descriptions of each character's role, motivations, and interactions ranked by narrative importance.",
  },
  {
    name: 'extract_controversial_ideas',
    description:
      'Extracts and outputs controversial statements and supporting quotes from the input in a structured Markdown list.',
  },
  {
    name: 'extract_core_message',
    description:
      'Extracts and outputs a clear, concise sentence that articulates the core message of a given text or body of work.',
  },
  {
    name: 'extract_ctf_writeup',
    description: 'Extracts a short writeup from a warstory-like text about a cyber security engagement.',
  },
  {
    name: 'extract_domains',
    description:
      'Extracts domains and URLs from content to identify sources used for articles, newsletters, and other publications.',
  },
  {
    name: 'extract_ethical_framework',
    description:
      'Extracts and analyzes the implicit ethical framework embedded in any prescriptive text, checking internal consistency and whether it creates unwilling victims.',
  },
  {
    name: 'extract_extraordinary_claims',
    description:
      'Extracts and outputs a list of extraordinary claims from conversations, focusing on scientifically disputed or false statements.',
  },
  {
    name: 'extract_ideas',
    description:
      'Extracts and outputs all the key ideas from input, presented as 15-word bullet points in Markdown.',
  },
  {
    name: 'extract_insights',
    description:
      'Extracts and outputs the most powerful and insightful ideas from text, formatted as 16-word bullet points in the INSIGHTS section, also IDEAS section.',
  },
  {
    name: 'extract_insights_dm',
    description:
      'Extracts and outputs all valuable insights and a concise summary of the content, including key points and topics discussed.',
  },
  {
    name: 'extract_instructions',
    description:
      'Extracts clear, actionable step-by-step instructions and main objectives from instructional video transcripts, organizing them into a concise list.',
  },
  {
    name: 'extract_jokes',
    description:
      'Extracts jokes from text content, presenting each joke with its punchline in separate bullet points.',
  },
  {
    name: 'extract_latest_video',
    description: 'Extracts the latest video URL from a YouTube RSS feed and outputs the URL only.',
  },
  {
    name: 'extract_main_activities',
    description:
      'Extracts key events and activities from transcripts or logs, providing a summary of what happened.',
  },
  {
    name: 'extract_main_idea',
    description:
      'Extracts the main idea and key recommendation from the input, summarizing them in 15-word sentences.',
  },
  {
    name: 'extract_mcp_servers',
    description:
      'Identify and summarize Model Context Protocol (MCP) servers referenced in the input along with their key details.',
  },
  {
    name: 'extract_most_redeeming_thing',
    description:
      'Extracts the most redeeming aspect from an input, summarizing it in a single 15-word sentence.',
  },
  {
    name: 'extract_patterns',
    description:
      'Extracts and analyzes recurring, surprising, and insightful patterns from input, providing detailed analysis and advice for builders.',
  },
  {
    name: 'extract_poc',
    description:
      'Extracts proof of concept URLs and validation methods from security reports, providing the URL and command to run.',
  },
  {
    name: 'extract_predictions',
    description:
      'Extracts predictions from input, including specific details such as date, confidence level, and verification method.',
  },
  {
    name: 'extract_primary_problem',
    description: 'Extracts the primary problem with the world as presented in a given text or body of work.',
  },
  {
    name: 'extract_primary_solution',
    description: 'Extracts the primary solution for the world as presented in a given text or body of work.',
  },
  {
    name: 'extract_product_features',
    description:
      'Extracts and outputs a list of product features from the provided input in a bulleted format.',
  },
  {
    name: 'extract_questions',
    description:
      'Extracts and outputs all questions asked by the interviewer in a conversation or interview.',
  },
  {
    name: 'extract_recipe',
    description:
      'Extracts and outputs a recipe with a short meal description, ingredients with measurements, and preparation steps.',
  },
  {
    name: 'extract_recommendations',
    description:
      'Extracts and outputs concise, practical recommendations from a given piece of content in a bulleted list.',
  },
  {
    name: 'extract_references',
    description:
      'Extracts and outputs a bulleted list of references to art, stories, books, literature, and other sources from content.',
  },
  {
    name: 'extract_skills',
    description:
      'Extracts and classifies skills from a job description into a table, separating each skill and classifying it as either hard or soft.',
  },
  {
    name: 'extract_song_meaning',
    description:
      'Analyzes a song to provide a summary of its meaning, supported by detailed evidence from lyrics, artist commentary, and fan analysis.',
  },
  {
    name: 'extract_sponsors',
    description: 'Extracts and lists official sponsors and potential sponsors from a provided transcript.',
  },
  {
    name: 'extract_video_commerce_entities',
    description:
      'Identifies commercially relevant entities in a video transcript — products, tools, brands, services, and more — grouped by category with mention type, repetition signals, and top purchase candidates.',
  },
  {
    name: 'extract_videoid',
    description: 'Extracts and outputs the video ID from any given URL.',
  },
  {
    name: 'extract_wisdom',
    description:
      'Extracts surprising, insightful, and interesting information from text on topics like human flourishing, AI, learning, and more.',
  },
  {
    name: 'extract_wisdom_agents',
    description:
      'Extracts valuable insights, ideas, quotes, and references from content, emphasizing topics like human flourishing, AI, learning, and technology.',
  },
  {
    name: 'extract_wisdom_dm',
    description:
      'Extracts all valuable, insightful, and thought-provoking information from content, focusing on topics like human flourishing, AI, learning, and technology.',
  },
  {
    name: 'extract_wisdom_nometa',
    description:
      'Extracts insights, ideas, quotes, habits, facts, references, and recommendations from content, focusing on human flourishing, AI, technology, and related topics.',
  },
  {
    name: 'extract_wisdom_with_attribution',
    description:
      'Extracts insightful ideas and recommendations with speaker attribution for quotes, focusing on life wisdom and human flourishing.',
  },
  {
    name: 'find_female_life_partner',
    description:
      'Analyzes criteria for finding a female life partner and provides clear, direct, and poetic descriptions.',
  },
  {
    name: 'find_hidden_message',
    description:
      'Extracts overt and hidden political messages, justifications, audience actions, and a cynical analysis from content.',
  },
  {
    name: 'find_logical_fallacies',
    description:
      'Identifies and analyzes fallacies in arguments, classifying them as formal or informal with detailed reasoning.',
  },
  {
    name: 'fix_typos',
    description: 'Proofreads and corrects typos, spelling, grammar, and punctuation errors in text.',
  },
  {
    name: 'generate_code_rules',
    description:
      'Compile best-practice coding rules and guardrails for AI-assisted development workflows from the provided content.',
  },
  {
    name: 'generate_frontmatter',
    description:
      'Generates paste-ready YAML frontmatter for PKM notes, with title, aliases, tags, type, summary, and status fields.',
  },
  {
    name: 'get_wow_per_minute',
    description:
      'Determines the wow-factor of content per minute based on surprise, novelty, insight, value, and wisdom, measuring how rewarding the content is for the viewer.',
  },
  {
    name: 'greybeard_secure_prompt_engineer',
    description:
      'Creates secure, production-grade system prompts with NASA-style mission assurance, outputting hardened prompts, injection test suites, and evaluation rubrics.',
  },
  {
    name: 'heal_person',
    description:
      'Develops a comprehensive plan for spiritual and mental healing based on psychological profiles, providing personalized recommendations for mental health improvement and overall life enhancement.',
  },
  {
    name: 'humanize',
    description:
      'Rewrites AI-generated text to sound natural, conversational, and easy to understand, maintaining clarity and simplicity.',
  },
  {
    name: 'identify_dsrp_distinctions',
    description:
      'Encourages creative, systems-based thinking by exploring distinctions, boundaries, and their implications, drawing on insights from prominent systems thinkers.',
  },
  {
    name: 'identify_dsrp_perspectives',
    description:
      'Explores the concept of distinctions in systems thinking, focusing on how boundaries define ideas, influence understanding, and reveal or obscure insights.',
  },
  {
    name: 'identify_dsrp_relationships',
    description:
      'Encourages exploration of connections, distinctions, and boundaries between ideas, inspired by systems thinkers to reveal new insights and patterns in complex systems.',
  },
  {
    name: 'identify_dsrp_systems',
    description:
      'Encourages organizing ideas into systems of parts and wholes, inspired by systems thinkers to explore relationships and how changes in organization impact meaning and understanding.',
  },
  {
    name: 'identify_job_stories',
    description: 'Identifies key job stories or requirements for roles.',
  },
  {
    name: 'improve_academic_writing',
    description:
      'Refines text into clear, concise academic language while improving grammar, coherence, and clarity, with a list of changes.',
  },
  {
    name: 'improve_prompt',
    description:
      'Improves an LLM/AI prompt by applying expert prompt writing strategies for better results and clarity.',
  },
  {
    name: 'improve_report_finding',
    description:
      'Improves a penetration test security finding by providing detailed descriptions, risks, recommendations, references, quotes, and a concise summary in markdown format.',
  },
  {
    name: 'improve_writing',
    description:
      'Refines text by correcting grammar, enhancing style, improving clarity, and maintaining the original meaning. skills.',
  },
  {
    name: 'judge_output',
    description:
      'Evaluates Honeycomb queries by judging their effectiveness, providing critiques and outcomes based on language nuances and analytics relevance.',
  },
  {
    name: 'label_and_rate',
    description:
      'Labels content with up to 20 single-word tags and rates it based on idea count and relevance to human meaning, AI, and other related themes, assigning a tier (S, A, B, C, D) and a quality score.',
  },
  {
    name: 'md_callout',
    description:
      'Classifies content and generates a markdown callout based on the provided text, selecting the most appropriate type.',
  },
  {
    name: 'model_as_sherlock_freud',
    description:
      'Builds psychological models using detective reasoning and psychoanalytic insight to understand human behavior.',
  },
  {
    name: 'official_pattern_template',
    description: 'Template to use if you want to create new fabric patterns.',
  },
  {
    name: 'predict_person_actions',
    description: 'Predicts behavioral responses based on psychological profiles and challenges.',
  },
  {
    name: 'prepare_7s_strategy',
    description:
      "Prepares a comprehensive briefing document from 7S's strategy capturing organizational profile, strategic elements, and market dynamics with clear, concise, and organized content.",
  },
  {
    name: 'provide_guidance',
    description:
      'Provides psychological and life coaching advice, including analysis, recommendations, and potential diagnoses, with a compassionate and honest tone.',
  },
  {
    name: 'rate_ai_response',
    description:
      'Rates the quality of AI responses by comparing them to top human expert performance, assigning a letter grade, reasoning, and providing a 1-100 score based on the evaluation.',
  },
  {
    name: 'rate_ai_result',
    description:
      'Assesses the quality of AI/ML/LLM work by deeply analyzing content, instructions, and output, then rates performance based on multiple dimensions, including coverage, creativity, and interdisciplinary thinking.',
  },
  {
    name: 'rate_content',
    description:
      'Labels content with up to 20 single-word tags and rates it based on idea count and relevance to human meaning, AI, and other related themes, assigning a tier (S, A, B, C, D) and a quality score.',
  },
  {
    name: 'rate_value',
    description:
      'Produces the best possible output by deeply analyzing and understanding the input and its intended purpose.',
  },
  {
    name: 'raw_query',
    description:
      "Fully digests and contemplates the input to produce the best possible result based on understanding the sender's intent.",
  },
  {
    name: 'recommend_artists',
    description:
      'Recommends a personalized festival schedule with artists aligned to your favorite styles and interests, including rationale.',
  },
  {
    name: 'recommend_pipeline_upgrades',
    description:
      'Optimizes vulnerability-checking pipelines by incorporating new information and improving their efficiency, with detailed explanations of changes.',
  },
  {
    name: 'recommend_talkpanel_topics',
    description:
      'Produces a clean set of proposed talks or panel talking points for a person based on their interests and goals, formatted for submission to a conference organizer.',
  },
  {
    name: 'recommend_yoga_practice',
    description:
      'Provides personalized yoga sequences, meditation guidance, and holistic lifestyle advice based on individual profiles.',
  },
  {
    name: 'refine_design_document',
    description:
      'Refines a design document based on a design review by analyzing, mapping concepts, and implementing changes using valid Markdown.',
  },
  {
    name: 'review_code',
    description:
      'Performs a comprehensive code review, providing detailed feedback on correctness, security, and performance.',
  },
  {
    name: 'review_design',
    description:
      'Reviews and analyzes architecture design, focusing on clarity, component design, system integrations, security, performance, scalability, and data management.',
  },
  {
    name: 'sanitize_broken_html_to_markdown',
    description:
      'Converts messy HTML into clean, properly formatted Markdown, applying custom styling and ensuring compatibility with Vite.',
  },
  {
    name: 'suggest_gt_command',
    description: 'Suggest optimal Gas Town (GT) commands based on user intent and task description.',
  },
  {
    name: 'suggest_openclaw_pattern',
    description:
      'Suggests the most appropriate Openclaw CLI command based on user intent, mapping natural language requests to commands for messaging, device management, scheduling, and automation.',
  },
  {
    name: 'suggest_pattern',
    description:
      'Suggests appropriate fabric patterns or commands based on user input, providing clear explanations and options for users.',
  },
  {
    name: 'summarize',
    description:
      'Summarizes content into a 20-word sentence, main points, and takeaways, formatted with numbered lists in Markdown.',
  },
  {
    name: 'summarize_board_meeting',
    description:
      'Creates formal meeting notes from board meeting transcripts for corporate governance documentation.',
  },
  {
    name: 'summarize_debate',
    description:
      'Summarizes debates, identifies primary disagreement, extracts arguments, and provides analysis of evidence and argument strength to predict outcomes.',
  },
  {
    name: 'summarize_git_changes',
    description:
      'Summarizes recent project updates from the last 7 days, focusing on key changes with enthusiasm.',
  },
  {
    name: 'summarize_git_diff',
    description:
      'Summarizes and organizes Git diff changes with clear, succinct commit messages and bullet points.',
  },
  {
    name: 'summarize_lecture',
    description:
      'Extracts relevant topics, definitions, and tools from lecture transcripts, providing structured summaries with timestamps and key takeaways.',
  },
  {
    name: 'summarize_legislation',
    description:
      'Summarizes complex political proposals and legislation by analyzing key points, proposed changes, and providing balanced, positive, and cynical characterizations.',
  },
  {
    name: 'summarize_meeting',
    description:
      'Analyzes meeting transcripts to extract a structured summary, including an overview, key points, tasks, decisions, challenges, timeline, references, and next steps.',
  },
  {
    name: 'summarize_micro',
    description:
      'Summarizes content into a 20-word sentence, 3 main points, and 3 takeaways, formatted in clear, concise Markdown.',
  },
  {
    name: 'summarize_newsletter',
    description:
      'Extracts the most meaningful, interesting, and useful content from a newsletter, summarizing key sections such as content, opinions, tools, companies, and follow-up items in clear, structured Markdown.',
  },
  {
    name: 'summarize_paper',
    description:
      'Summarizes an academic paper by detailing its title, authors, technical approach, distinctive features, experimental setup, results, advantages, limitations, and conclusion in a clear, structured format using human-readable Markdown.',
  },
  {
    name: 'summarize_prompt',
    description:
      "Summarizes AI chat prompts by describing the primary function, unique approach, and expected output in a concise paragraph. The summary is focused on the prompt's purpose without unnecessary details or formatting.",
  },
  {
    name: 'summarize_pull-requests',
    description:
      'Summarizes pull requests for a coding project by providing a summary and listing the top PRs with human-readable descriptions.',
  },
  {
    name: 'summarize_rpg_session',
    description:
      'Summarizes a role-playing game session by extracting key events, combat stats, character changes, quotes, and more.',
  },
  {
    name: 't_analyze_challenge_handling',
    description:
      'Provides 8-16 word bullet points evaluating how well challenges are being addressed, calling out any lack of effort.',
  },
  {
    name: 't_check_dunning_kruger',
    description:
      'Assess narratives for Dunning-Kruger patterns by contrasting self-perception with demonstrated competence and confidence cues.',
  },
  {
    name: 't_check_metrics',
    description:
      'Analyzes deep context from the TELOS file and input instruction, then provides a wisdom-based output while considering metrics and KPIs to assess recent improvements.',
  },
  {
    name: 't_create_h3_career',
    description:
      'Summarizes context and produces wisdom-based output by deeply analyzing both the TELOS File and the input instruction, considering the relationship between the two.',
  },
  {
    name: 't_create_opening_sentences',
    description:
      "Describes from TELOS file the person's identity, goals, and actions in 4 concise, 32-word bullet points, humbly.",
  },
  {
    name: 't_describe_life_outlook',
    description: "Describes from TELOS file a person's life outlook in 5 concise, 16-word bullet points.",
  },
  {
    name: 't_extract_intro_sentences',
    description:
      "Summarizes from TELOS file a person's identity, work, and current projects in 5 concise and grounded bullet points.",
  },
  {
    name: 't_extract_panel_topics',
    description:
      'Creates 5 panel ideas with titles and descriptions based on deep context from a TELOS file and input.',
  },
  {
    name: 't_find_blindspots',
    description:
      'Identify potential blindspots in thinking, frames, or models that may expose the individual to error or risk.',
  },
  {
    name: 't_find_negative_thinking',
    description:
      'Analyze a TELOS file and input to identify negative thinking in documents or journals, followed by tough love encouragement.',
  },
  {
    name: 't_find_neglected_goals',
    description:
      'Analyze a TELOS file and input instructions to identify goals or projects that have not been worked on recently.',
  },
  {
    name: 't_give_encouragement',
    description:
      'Analyze a TELOS file and input instructions to evaluate progress, provide encouragement, and offer recommendations for continued effort.',
  },
  {
    name: 't_red_team_thinking',
    description:
      'Analyze a TELOS file and input instructions to red-team thinking, models, and frames, then provide recommendations for improvement.',
  },
  {
    name: 't_threat_model_plans',
    description:
      'Analyze a TELOS file and input instructions to create threat models for a life plan and recommend improvements.',
  },
  {
    name: 't_visualize_mission_goals_projects',
    description:
      'Analyze a TELOS file and input instructions to create an ASCII art diagram illustrating the relationship of missions, goals, and projects.',
  },
  {
    name: 't_year_in_review',
    description:
      'Analyze a TELOS file to create insights about a person or entity, then summarize accomplishments and visualizations in bullet points.',
  },
  {
    name: 'to_flashcards',
    description:
      'Create Anki flashcards from a given text, focusing on concise, optimized questions and answers without external context.',
  },
  {
    name: 'transcribe_minutes',
    description:
      'Extracts (from meeting transcription) meeting minutes, identifying actionables, insightful ideas, decisions, challenges, and next steps in a structured format.',
  },
  {
    name: 'translate',
    description:
      'Translates sentences or documentation into the specified language code while maintaining the original formatting and tone.',
  },
  {
    name: 'tweet',
    description:
      'Provides a step-by-step guide on crafting engaging tweets with emojis, covering Twitter basics, account creation, features, and audience targeting.',
  },
  {
    name: 'ultimate_law_safety',
    description:
      'Evaluates actions, policies, or systems against the Ultimate Law framework — a minimal, falsifiable ethical constraint that prohibits creating unwilling victims.',
  },
  {
    name: 'write_essay',
    description:
      'Writes essays in the style of a specified author, embodying their unique voice, vocabulary, and approach. Uses `author_name` variable.',
  },
  {
    name: 'write_essay_pg',
    description:
      'Writes concise, clear essays in the style of Paul Graham, focusing on simplicity, clarity, and illumination of the provided topic.',
  },
  {
    name: 'write_hackerone_report',
    description:
      'Generates concise, clear, and reproducible bug bounty reports, detailing vulnerability impact, steps to reproduce, and exploit details for triagers.',
  },
  {
    name: 'write_latex',
    description:
      'Generates syntactically correct LaTeX code for a new.tex document, ensuring proper formatting and compatibility with pdflatex.',
  },
  {
    name: 'write_micro_essay',
    description:
      'Writes concise, clear, and illuminating essays on the given topic in the style of Paul Graham.',
  },
  {
    name: 'write_nuclei_template_rule',
    description:
      'Generates Nuclei YAML templates for detecting vulnerabilities using HTTP requests, matchers, extractors, and dynamic data extraction.',
  },
  {
    name: 'write_pull-request',
    description:
      'Drafts detailed pull request descriptions, explaining changes, providing reasoning, and identifying potential bugs from the git diff command output.',
  },
  {
    name: 'write_semgrep_rule',
    description:
      'Creates accurate and working Semgrep rules based on input, following syntax guidelines and specific language considerations.',
  },
  {
    name: 'youtube_summary',
    description: 'Create concise, timestamped Youtube video summaries that highlight key points.',
  },
];
