import { writeFile } from 'node:fs/promises';

const commit = 'b682dad740f24e85ce9a48d23babc6780dd476ac';
const response = await fetch(
  `https://raw.githubusercontent.com/danielmiessler/fabric/${commit}/data/patterns/pattern_explanations.md`,
);
if (!response.ok) throw new Error(`Fabric index request failed: HTTP ${response.status}`);
const markdown = await response.text();
const patterns = [...markdown.matchAll(/^\d+\. \*\*([^*]+)\*\*: (.+)\r?$/gm)]
  .map((match) => ({ name: match[1], description: match[2].trim() }))
  .sort((a, b) => a.name.localeCompare(b.name));
if (patterns.length < 200) throw new Error(`Fabric index parsed only ${patterns.length} entries`);

await writeFile(
  new URL('../src/ai/fabric-index.ts', import.meta.url),
  `// Generated by npm run fetch-fabric. Do not edit manually.\n` +
    `export const FABRIC_COMMIT = '${commit}';\n` +
    `export const FABRIC_PATTERNS: { name: string; description: string }[] = ${JSON.stringify(patterns, null, 2)};\n`,
);
console.log(`Generated ${patterns.length} Fabric patterns`);
